# Generated by Django 4.0.4 on 2022-06-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuarios_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='usuarios',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table=None,
        ),
    ]
