# Generated by Django 4.0.4 on 2022-06-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_usuarios_options_alter_usuarios_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['UserAcces'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterUniqueTogether(
            name='usuario',
            unique_together={('UserAcces',)},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='Usuario',
        ),
    ]
