# Generated by Django 4.0.4 on 2022-06-04 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_usuarios_usuario_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario',
            table='Usuarios',
        ),
    ]
