# Generated by Django 4.0.4 on 2022-06-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuario_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=2, verbose_name='Edificio')),
                ('coordenadas', models.CharField(max_length=255, verbose_name='Coordenadas')),
                ('etiqueta_x', models.CharField(max_length=5, verbose_name='Etiqueta X')),
                ('etiqueta_y', models.CharField(max_length=5, verbose_name='Etiqueta Y')),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
                'db_table': 'Edificio',
                'ordering': ['numero'],
                'unique_together': {('numero',)},
            },
        ),
    ]
