# Generated by Django 4.0.4 on 2022-06-04 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_edificio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='edificio',
            table='edificio',
        ),
    ]
