# Generated by Django 4.0.4 on 2022-06-04 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_edificio_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recibo', models.CharField(max_length=30, verbose_name='Número de recibo')),
                ('edificio', models.CharField(max_length=2, verbose_name='Edificio')),
                ('depto', models.CharField(max_length=3, verbose_name='Departamento')),
                ('recibimos_de', models.CharField(max_length=90, verbose_name='Departamento')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Importe')),
                ('concepto', models.CharField(max_length=500, verbose_name='Concepto')),
                ('fecha_pago', models.DateField(auto_now_add=True, null=True, verbose_name='FecahPago')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'Recibo',
                'ordering': ['edificio', 'depto', '-created'],
            },
        ),
        migrations.DeleteModel(
            name='Edificio',
        ),
    ]
